# -*- coding: utf-8 -*-
"""Cardiovascular_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hPo4f5RKyT6nbE8cgc6gij4-4qHbNEU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    ConfusionMatrixDisplay
)

df = pd.read_csv("cardio_train.csv", sep=";")

print("Quantidade de linhas:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])

df.head()

print("Dimensões:", df.shape)

print("\nTipos de dados:")
print(df.dtypes)

print("\nValores ausentes:")
print(df.isnull().sum())

print("\nLinhas duplicadas:")
print(df.duplicated().sum())

print("\nDistribuição da variável alvo:")
print(df["cardio"].value_counts())

counts = df["cardio"].value_counts().sort_index()

plt.figure(figsize=(7, 5))

plt.bar(
    ["Sem doença (0)", "Com doença (1)"],
    counts.values
)

plt.title("Distribuição das Classes")
plt.ylabel("Quantidade de registros")

for i, valor in enumerate(counts.values):
    plt.text(i, valor + 200, str(valor), ha="center")

plt.tight_layout()
plt.show()

colunas_numericas = [
    "age",
    "height",
    "weight",
    "ap_hi",
    "ap_lo"
]

print(df[colunas_numericas].describe())

mask = (
    df["height"].between(120, 220) &
    df["weight"].between(30, 200) &
    df["ap_hi"].between(80, 250) &
    df["ap_lo"].between(40, 150) &
    (df["ap_hi"] > df["ap_lo"])
)

dados = df.loc[mask].copy()

print("Antes da limpeza:", len(df))
print("Depois da limpeza:", len(dados))
print("Registros removidos:", len(df) - len(dados))

dados["age_years"] = dados["age"] / 365.25

dados["bmi"] = (
    dados["weight"] /
    (dados["height"] / 100) ** 2
)

dados[["age", "age_years", "height", "weight", "bmi"]].head()

counts = dados["cardio"].value_counts().sort_index()

plt.figure(figsize=(7, 5))

plt.bar(
    ["Sem doença (0)", "Com doença (1)"],
    counts.values
)

plt.title("Distribuição das Classes — Dataset Limpo")
plt.ylabel("Quantidade")

for i, valor in enumerate(counts.values):
    plt.text(i, valor + 200, str(valor), ha="center")

plt.tight_layout()
plt.show()

features = [
    "age_years",
    "gender",
    "height",
    "weight",
    "ap_hi",
    "ap_lo",
    "cholesterol",
    "gluc",
    "smoke",
    "alco",
    "active",
    "bmi"
]

X = dados[features]
y = dados["cardio"]

print("Variáveis utilizadas:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Treinamento:", len(X_train))
print("Teste:", len(X_test))

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

pipeline_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=2000))
])

parametros_lr = {
    "model__C": [0.01, 0.1, 1, 10],
    "model__solver": ["liblinear", "lbfgs"]
}

grid_lr = GridSearchCV(
    pipeline_lr,
    parametros_lr,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

grid_lr.fit(X_train, y_train)

print("Melhores parâmetros:")
print(grid_lr.best_params_)

print("Melhor F1 na validação:")
print(grid_lr.best_score_)

pipeline_knn = Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier())
])

parametros_knn = {
    "model__n_neighbors": [5, 11, 21, 31],
    "model__weights": ["uniform", "distance"],
    "model__p": [1, 2]
}

grid_knn = GridSearchCV(
    pipeline_knn,
    parametros_knn,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

grid_knn.fit(X_train, y_train)

print("Melhores parâmetros:")
print(grid_knn.best_params_)

print("Melhor F1 na validação:")
print(grid_knn.best_score_)

pred_lr = grid_lr.predict(X_test)
prob_lr = grid_lr.predict_proba(X_test)[:, 1]

pred_knn = grid_knn.predict(X_test)
prob_knn = grid_knn.predict_proba(X_test)[:, 1]

resultados = pd.DataFrame({
    "Modelo": [
        "Regressão Logística",
        "KNN"
    ],

    "Accuracy": [
        accuracy_score(y_test, pred_lr),
        accuracy_score(y_test, pred_knn)
    ],

    "Precision": [
        precision_score(y_test, pred_lr),
        precision_score(y_test, pred_knn)
    ],

    "Recall": [
        recall_score(y_test, pred_lr),
        recall_score(y_test, pred_knn)
    ],

    "F1-Score": [
        f1_score(y_test, pred_lr),
        f1_score(y_test, pred_knn)
    ],

    "ROC-AUC": [
        roc_auc_score(y_test, prob_lr),
        roc_auc_score(y_test, prob_knn)
    ]
})

print((resultados.set_index("Modelo") * 100).round(2))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    pred_lr,
    display_labels=[
        "Sem doença",
        "Com doença"
    ],
    values_format="d"
)

plt.title(
    "Matriz de Confusão — Regressão Logística"
)

plt.tight_layout()
plt.show()

ConfusionMatrixDisplay.from_predictions(
    y_test,
    pred_knn,
    display_labels=[
        "Sem doença",
        "Com doença"
    ],
    values_format="d"
)

plt.title(
    "Matriz de Confusão — KNN"
)

plt.tight_layout()
plt.show()

resultados_plot = resultados.set_index("Modelo") * 100

resultados_plot.plot(
    kind="bar",
    figsize=(10, 6)
)

plt.title(
    "Comparação de Desempenho dos Modelos"
)

plt.ylabel("Resultado (%)")
plt.xlabel("")

plt.ylim(0, 100)

plt.xticks(rotation=0)

plt.legend(
    title="Métrica",
    loc="lower right"
)

plt.tight_layout()
plt.show()

fpr_lr, tpr_lr, _ = roc_curve(
    y_test,
    prob_lr
)

fpr_knn, tpr_knn, _ = roc_curve(
    y_test,
    prob_knn
)

auc_lr = roc_auc_score(
    y_test,
    prob_lr
)

auc_knn = roc_auc_score(
    y_test,
    prob_knn
)

plt.figure(figsize=(7, 6))

plt.plot(
    fpr_lr,
    tpr_lr,
    label=f"Regressão Logística (AUC={auc_lr:.3f})"
)

plt.plot(
    fpr_knn,
    tpr_knn,
    label=f"KNN (AUC={auc_knn:.3f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Referência aleatória"
)

plt.title("Curva ROC")
plt.xlabel("Taxa de Falsos Positivos")
plt.ylabel("Taxa de Verdadeiros Positivos")

plt.legend()

plt.tight_layout()
plt.show()

coeficientes = pd.Series(
    grid_lr
        .best_estimator_
        .named_steps["model"]
        .coef_[0],

    index=features
)

coeficientes.sort_values().plot(
    kind="barh",
    figsize=(9, 6)
)

plt.title(
    "Coeficientes — Regressão Logística"
)

plt.xlabel("Coeficiente")

plt.tight_layout()
plt.show()